version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.1
  aws-ecr: circleci/aws-ecr@3.0.0

jobs:
  build:
    docker:
    - image: circleci/python
    steps:
    - checkout
    - setup_remote_docker
    - aws-cli/install
    - aws-cli/configure
    - aws-ecr/ecr-login
    - run:
        name: Build Docker images
        command: |
          docker build -t $AWS_ECR_ACCOUNT_URL/ec2-blog-fpm:latest -t $AWS_ECR_ACCOUNT_URL/ec2-blog-fpm:$CIRCLE_SHA1 --target app .
          docker build -t $AWS_ECR_ACCOUNT_URL/ec2-blog-web:latest -t $AWS_ECR_ACCOUNT_URL/ec2-blog-web:$CIRCLE_SHA1 --target web .
    - run:
        name: Push images to Amazon ECR
        command: |
          docker push $AWS_ECR_ACCOUNT_URL/ec2-blog-fpm:latest
          docker push $AWS_ECR_ACCOUNT_URL/ec2-blog-fpm:$CIRCLE_SHA1
          docker push $AWS_ECR_ACCOUNT_URL/ec2-blog-web:latest
          docker push $AWS_ECR_ACCOUNT_URL/ec2-blog-web:$CIRCLE_SHA1

workflows:
  version: 2
  main:
    jobs:
    - build:
        context: amazon-ecr
        filters:
          branches:
            only: master